# default image
image: node:12

# continuous integration flows
stages:
  - package
  - deploy

# global cache
cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

# build the project
build:
  stage: package
  before_script:
    - yarn
  script:
    - yarn build
  after_script:
    - echo "The build process is successful."
  artifacts:
    paths:
      - ./dist
    expire_in: 15 minutes
  only:
    refs:
      - master
      - develop

# deploy on production server
production:
  stage: deploy
  before_script:
    - npm install -g firebase-tools
  script:
    - firebase deploy --only hosting:web --non-interactive --token "$FIREBASE_TOKEN"
  after_script:
    - echo "The code is deployed to production server."
  only:
    refs:
      - master
  when: manual
